REM python src/main.py --output_dir experiments_regression --comment "regression BeijingPM10Quality" --name BeijingPM10Quality_Regression --records_file Regression_records.xls --data_dir TransformerDatasetsRegression/BeijingPM10Quality/ --data_class tsra --pattern TRAIN --val_pattern TEST --epochs 100 --lr 0.001 --optimizer RAdam  --pos_encoding learnable --task regression --batch_size 32 --d_model 128
REM python src/main.py --output_dir experiments_regression --comment "pretraining BeijingPM10Quality" --name BeijingPM10Quality_pretrained --records_file Imputation_Regression_records.xls --data_dir TransformerDatasetsRegression/BeijingPM10Quality/ --data_class tsra --pattern TRAIN --val_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 32 --pos_encoding learnable --d_model 128
REM python src/main.py --output_dir experiments_regression --comment "regression BeijingPM25Quality" --name BeijingPM25Quality_Regression --records_file Regression_records.xls --data_dir TransformerDatasetsRegression/BeijingPM25Quality/ --data_class tsra --pattern TRAIN --val_pattern TEST --epochs 100 --lr 0.001 --optimizer RAdam  --pos_encoding learnable --task regression --batch_size 32 --d_model 128
REM python src/main.py --output_dir experiments_regression --comment "pretraining BeijingPM25Quality" --name BeijingPM25Quality_pretrained --records_file Imputation_Regression_records.xls --data_dir TransformerDatasetsRegression/BeijingPM25Quality/ --data_class tsra --pattern TRAIN --val_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 32 --pos_encoding learnable --d_model 128
REM python src/main.py --output_dir experiments_regression --comment "regression AppliancesEnergy" --name AppliancesEnergy_Regression --records_file Regression_records.xls --data_dir TransformerDatasetsRegression/AppliancesEnergy/ --data_class tsra --pattern TRAIN --val_pattern TEST --epochs 100 --lr 0.001 --optimizer RAdam  --pos_encoding learnable --task regression --batch_size 32 --d_model 128
REM python src/main.py --output_dir experiments_regression --comment "pretraining AppliancesEnergy" --name AppliancesEnergy_pretrained --records_file Imputation_Regression_records.xls --data_dir TransformerDatasetsRegression/AppliancesEnergy/ --data_class tsra --pattern TRAIN --val_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 32 --pos_encoding learnable --d_model 128
python src/main.py --output_dir experiments_regression --comment "regression IEEEPPG" --name IEEEPPG_Regression --records_file Regression_records.xls --data_dir TransformerDatasetsRegression/IEEEPPG/ --data_class tsra --pattern TRAIN --val_pattern TEST --epochs 100 --lr 0.001 --optimizer RAdam  --pos_encoding learnable --task regression --batch_size 32 --d_model 128
python src/main.py --output_dir experiments_regression --comment "pretraining IEEEPPG" --name IEEEPPG_pretrained --records_file Imputation_Regression_records.xls --data_dir TransformerDatasetsRegression/IEEEPPG/ --data_class tsra --pattern TRAIN --val_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 32 --pos_encoding learnable --d_model 128
python src/main.py --output_dir experiments_regression --comment "regression LiveFuelMoistureContent" --name LiveFuelMoistureContent_Regression --records_file Regression_records.xls --data_dir TransformerDatasetsRegression/LiveFuelMoistureContent/ --data_class tsra --pattern TRAIN --val_pattern TEST --epochs 100 --lr 0.001 --optimizer RAdam  --pos_encoding learnable --task regression --batch_size 32 --d_model 128
python src/main.py --output_dir experiments_regression --comment "pretraining LiveFuelMoistureContent" --name LiveFuelMoistureContent_pretrained --records_file Imputation_Regression_records.xls --data_dir TransformerDatasetsRegression/LiveFuelMoistureContent/ --data_class tsra --pattern TRAIN --val_ratio 0.2 --epochs 100 --lr 0.001 --optimizer RAdam --batch_size 32 --pos_encoding learnable --d_model 128




PAUSE